[package]
name = "old-gun"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = [] }
rand = "0.8"

[build-dependencies]
fs_extra = "1.2"

[profile.dev]
opt-level = 1
