[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
bevy_dylib = "0.15"
bevy_utils = "0.15"
rand = "0.8"

[profile.dev]
opt-level = 1
