[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bevy = { version = "0.15", features = ["dynamic_linking"] }
bevy_dylib = "0.15"
bevy_embedded_assets = "0.12"
bevy_prototype_lyon = "0.13"
directories = "6"
rand = "0.8"

[profile.dev]
opt-level = 1
