[package]
name = "floppy-corgi"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_asset_loader = { version = "0.22", features = ["2d"] }
bevy_transform_interpolation = "0.1"
noise = "0.9"
