[package]
name = "soukoban-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
bevy_dylib = "0.15"
soukoban = { path = "../soukoban" }
